[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = [ "py", "pyi", "pyc", "pyd", "pyw" ]
shebangs = [ "python" ]
roots = [ "pyproject.toml" ]
comment-token = "#"
auto-format = true
formatter = { command = "ruff", args = ["format", "--quiet", "-"] }
language-servers = [ "ruff", "pyright" ]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
pythonVersion = "3.12"
venvPath = "."
venv = ".venv"
include = ["./src"]
exclude = ["**/node_modules", "**/__pycache__"]
ignore = []
stubPath = "./stubs"
reportMissingImports = true
reportMissingTypeStubs = false
userFileIndexingLimit = -1
useLibraryCodeForTypes = true

[language-server.ruff]
command = "ruff"
config = { settings = { args = ["server"] } }
